Algoritmo CONAGUA
	DEFINIR METROSCUBICOS,TARIFA,PAGO Como Real
	TARIFA <-10.5
	ESCRIBIR"INGRESE LA CANTIDAD DE METROS CUBICOS CONSUMIDOS"
	LEER METROSCUBICOS 
	
	PAGO<-METROSCUBICOS*TARIFA
	
	ESCRIBIR"EL PAGO TOTAL ES:" PAGO
	
FinAlgoritmo
